"""`.env` loading/creation, key generation, and GPU-cap detection.

The `.env` is the operator's runtime config (gitignored). Created from
`.env.example` on first run; values are plain `KEY=VALUE`. The slim schema:
SERVER_HOSTNAME, API_KEY, MLX_HOST, HF_HOME, IOGPU_WIRED_LIMIT_MB.
"""

from __future__ import annotations

import secrets
from pathlib import Path

SCHEMA = ["SERVER_HOSTNAME", "API_KEY", "MLX_HOST", "SHIM_HOST", "HF_HOME",
          "IOGPU_WIRED_LIMIT_MB"]

GPU_HEADROOM_MB = 8192  # leave ~8 GB for macOS


def parse_env(text: str) -> dict:
    env = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env[key.strip()] = value.strip()
    return env


def load_env(path) -> dict:
    p = Path(path)
    return parse_env(p.read_text()) if p.exists() else {}


def ensure_env(path, example_path) -> dict:
    """Create `.env` from the example when absent; return the parsed dict."""
    p = Path(path)
    if not p.exists():
        p.write_text(Path(example_path).read_text())
    return load_env(p)


def write_env(path, values: dict) -> None:
    lines = ["# Generated by llmctl — edit values, not the layout."]
    lines += [f"{k}={values.get(k, '')}" for k in SCHEMA]
    Path(path).write_text("\n".join(lines) + "\n")


def generate_api_key() -> str:
    return secrets.token_hex(16)


def detect_gpu_cap_mb(effects, headroom_mb: int = GPU_HEADROOM_MB) -> int:
    total_bytes = int(effects.run(["sysctl", "-n", "hw.memsize"]).stdout.strip())
    return total_bytes // (1024 * 1024) - headroom_mb
